name: Build and deploy a container to an Azure Web App

env:
  AZURE_WEBAPP_NAME: 'appneymar'       
  ACR_NAME: 'conteiney-facwhxb2fmfre6hc' # Altere aqui (repare que tiramos o .azurecr.io do final)
  IMAGE_NAME: 'conteiney-facwhxb2fmfre6hc.azurecr.io/minha-app' # Altere aqui também com o  

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login no Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login no ACR
        run: az acr login --name ${{ env.ACR_NAME }}

      - name: Build Docker
        run: |
          docker build -t ${{ env.IMAGE_NAME }}:${{ github.sha }} -t ${{ env.IMAGE_NAME }}:latest .

      - name: Push Docker
        run: |
          docker push ${{ env.IMAGE_NAME }}:${{ github.sha }}
          docker push ${{ env.IMAGE_NAME }}:latest

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build 
    environment:
      name: 'Development'

    steps:
      - name: Login no Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          images: '${{ env.IMAGE_NAME }}:latest'
